# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='oscovida',
    version='0.1.2',
    description='Explore COVID19 case numbers and deaths related to Coronavirus outbreak 2019/2020 in Pandas and in Jupyter notebook with MyBinder',
    python_requires='==3.*,>=3.6.7',
    author='Hans Fangohr',
    author_email='da-support@xfel.eu',
    maintainer='Hans Fangohr',
    packages=['oscovida'],
    package_dir={"": "."},
    package_data={},
    install_requires=[
        'click==7.*,>=7.1.2',
        'ipynb-py-convert==0.*,>=0.4.5',
        'ipywidgets==7.*,>=7.5.1',
        'joblib==0.*,>=0.16.0',
        'markdown==3.*,>=3.2.2',
        'matplotlib<3.3',
        'numpy==1.*,>=1.19.0',
        'pandas==1.*,>=1.0.5',
        'pelican==4.*,>=4.2.0',
        'pelican-jupyter==0.*,>=0.10.0',
        'scipy==1.*,>=1.5.1',
        'seaborn==0.*,>=0.10.1',
        'tabulate==0.*,>=0.8.7',
        'tqdm==4.*,>=4.48.0',
        'voila==0.*,>=0.1.21',
    ],
    extras_require={
        "dev": [
            "black==19.*,>=19.10.0.b0",
            "coverage==5.*,>=5.2.0",
            "mypy==0.*,>=0.782.0",
            "nbval==0.*,>=0.9.5",
            "pycodestyle==2.*,>=2.6.0",
            "pytest==5.*,>=5.4.3",
            "pytest-cov==2.*,>=2.10.0",
            "testpath==0.*,>=0.4.4",
        ],
        "formatting": [
            "black==19.*,>=19.10.0.b0",
            "mypy==0.*,>=0.782.0",
            "pycodestyle==2.*,>=2.6.0",
        ],
        "test": [
            "coverage==5.*,>=5.2.0",
            "nbval==0.*,>=0.9.5",
            "pytest==5.*,>=5.4.3",
            "pytest-cov==2.*,>=2.10.0",
            "testpath==0.*,>=0.4.4",
        ],
    },
)
